name: tests
on:
  push:
    tags:
      - v*
    branches:
      - master
      - '**'
  pull_request:
  workflow_dispatch:
jobs:
  basic:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    services:
      ydb:
        image: cr.yandex/yc/yandex-docker-local-ydb:latest
        ports:
          - 2135:2135
          - 8765:8765
        volumes:
          - /tmp/ydb_certs:/ydb_certs
        env:
          YDB_LOCAL_SURVIVE_RESTART: true
          YDB_USE_IN_MEMORY_PDISKS: true
        options: '-h localhost'
    env:
      OS: ${{ matrix.os }}
      GO: ${{ matrix.go-version }}
      YDB_CONNECTION_STRING: grpcs://localhost:2135/?database=/local
      YDB_SSL_ROOT_CERTIFICATES_FILE: /tmp/ydb_certs/ca.pem
      YDB_ANONYMOUS_CREDENTIALS: 1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go run ./basic -ydb=${YDB_CONNECTION_STRING} -prefix=basic
  bulk_upsert:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    services:
      ydb:
        image: cr.yandex/yc/yandex-docker-local-ydb:latest
        ports:
          - 2135:2135
          - 8765:8765
        volumes:
          - /tmp/ydb_certs:/ydb_certs
        env:
          YDB_LOCAL_SURVIVE_RESTART: true
          YDB_USE_IN_MEMORY_PDISKS: true
        options: '-h localhost'
    env:
      OS: ${{ matrix.os }}
      GO: ${{ matrix.go-version }}
      YDB_CONNECTION_STRING: grpcs://localhost:2135/?database=/local
      YDB_SSL_ROOT_CERTIFICATES_FILE: /tmp/ydb_certs/ca.pem
      YDB_ANONYMOUS_CREDENTIALS: 1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go run ./bulk_upsert -ydb=${YDB_CONNECTION_STRING} -prefix=bulk_upsert -count=1000 -table=bulk_upsert_example
  containers:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    services:
      ydb:
        image: cr.yandex/yc/yandex-docker-local-ydb:latest
        ports:
          - 2135:2135
          - 8765:8765
        volumes:
          - /tmp/ydb_certs:/ydb_certs
        env:
          YDB_LOCAL_SURVIVE_RESTART: true
          YDB_USE_IN_MEMORY_PDISKS: true
        options: '-h localhost'
    env:
      OS: ${{ matrix.os }}
      GO: ${{ matrix.go-version }}
      YDB_CONNECTION_STRING: grpcs://localhost:2135/?database=/local
      YDB_SSL_ROOT_CERTIFICATES_FILE: /tmp/ydb_certs/ca.pem
      YDB_ANONYMOUS_CREDENTIALS: 1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go run ./containers -ydb=${YDB_CONNECTION_STRING} -prefix=containers
  ddl:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    services:
      ydb:
        image: cr.yandex/yc/yandex-docker-local-ydb:latest
        ports:
          - 2135:2135
          - 8765:8765
        volumes:
          - /tmp/ydb_certs:/ydb_certs
        env:
          YDB_LOCAL_SURVIVE_RESTART: true
          YDB_USE_IN_MEMORY_PDISKS: true
        options: '-h localhost'
    env:
      OS: ${{ matrix.os }}
      GO: ${{ matrix.go-version }}
      YDB_CONNECTION_STRING: grpcs://localhost:2135/?database=/local
      YDB_SSL_ROOT_CERTIFICATES_FILE: /tmp/ydb_certs/ca.pem
      YDB_ANONYMOUS_CREDENTIALS: 1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go run ./ddl -ydb=${YDB_CONNECTION_STRING} -prefix=ddl
  decimal:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    services:
      ydb:
        image: cr.yandex/yc/yandex-docker-local-ydb:latest
        ports:
          - 2135:2135
          - 8765:8765
        volumes:
          - /tmp/ydb_certs:/ydb_certs
        env:
          YDB_LOCAL_SURVIVE_RESTART: true
          YDB_USE_IN_MEMORY_PDISKS: true
        options: '-h localhost'
    env:
      OS: ${{ matrix.os }}
      GO: ${{ matrix.go-version }}
      YDB_CONNECTION_STRING: grpcs://localhost:2135/?database=/local
      YDB_SSL_ROOT_CERTIFICATES_FILE: /tmp/ydb_certs/ca.pem
      YDB_ANONYMOUS_CREDENTIALS: 1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go run ./decimal -ydb=${YDB_CONNECTION_STRING} -prefix=decimal
  healthcheck:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    services:
      ydb:
        image: cr.yandex/yc/yandex-docker-local-ydb:latest
        ports:
          - 2135:2135
          - 8765:8765
        volumes:
          - /tmp/ydb_certs:/ydb_certs
        env:
          YDB_LOCAL_SURVIVE_RESTART: true
          YDB_USE_IN_MEMORY_PDISKS: true
        options: '-h localhost'
    env:
      OS: ${{ matrix.os }}
      GO: ${{ matrix.go-version }}
      YDB_CONNECTION_STRING: grpcs://localhost:2135/?database=/local
      YDB_SSL_ROOT_CERTIFICATES_FILE: /tmp/ydb_certs/ca.pem
      YDB_ANONYMOUS_CREDENTIALS: 1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go run ./healthcheck -ydb=${YDB_CONNECTION_STRING} -prefix=healthcheck -count=1 -url=yandex.ru -url=google.com
  pagination:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    services:
      ydb:
        image: cr.yandex/yc/yandex-docker-local-ydb:latest
        ports:
          - 2135:2135
          - 8765:8765
        volumes:
          - /tmp/ydb_certs:/ydb_certs
        env:
          YDB_LOCAL_SURVIVE_RESTART: true
          YDB_USE_IN_MEMORY_PDISKS: true
        options: '-h localhost'
    env:
      OS: ${{ matrix.os }}
      GO: ${{ matrix.go-version }}
      YDB_CONNECTION_STRING: grpcs://localhost:2135/?database=/local
      YDB_SSL_ROOT_CERTIFICATES_FILE: /tmp/ydb_certs/ca.pem
      YDB_ANONYMOUS_CREDENTIALS: 1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go run ./pagination -ydb=${YDB_CONNECTION_STRING} -prefix=pagination
  partitioning_policies:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    services:
      ydb:
        image: cr.yandex/yc/yandex-docker-local-ydb:latest
        ports:
          - 2135:2135
          - 8765:8765
        volumes:
          - /tmp/ydb_certs:/ydb_certs
        env:
          YDB_LOCAL_SURVIVE_RESTART: true
          YDB_USE_IN_MEMORY_PDISKS: true
        options: '-h localhost'
    env:
      OS: ${{ matrix.os }}
      GO: ${{ matrix.go-version }}
      YDB_CONNECTION_STRING: grpcs://localhost:2135/?database=/local
      YDB_SSL_ROOT_CERTIFICATES_FILE: /tmp/ydb_certs/ca.pem
      YDB_ANONYMOUS_CREDENTIALS: 1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go run ./partitioning_policies -ydb=${YDB_CONNECTION_STRING} -prefix=partitioning_policies
